# **Assignment For Numpy**

# Name:- Shehroz Shahid

# Roll No. :- PIAIC105655

# Q 2 Batch 13 Multan

# Note:- use jupyter binder use please accepted

Difficulty Level **Beginner**

In [6]:
pip install numpy

Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.19.4)
Note: you may need to restart the kernel to use updated packages.

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
np.shape(arr)

(40,)

5. Print the type of the previous array in question 3

In [7]:
type(arr)

numpy.ndarray

6. Print the numpy version and the configuration

In [9]:
print("Version: ",np.__version__)
print("Configuration: ",np.show_config())

Version:  1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Configuration:  None

7. Print the dimension of the array in question 3

In [10]:
 np.ndim(arr)

1

8. Create a boolean array with all the True values

In [13]:
np.ones((4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

9. Create a two dimensional array

In [14]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array

In [15]:
arr3d=np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
vector=np.arange(20)
print("Vector: ",vector)
reverse_vector=vector[::-1]
print("Reverse_Vector: ",reverse_vector)

Vector:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse_Vector:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

12. Create a null vector of size 10 but the fifth value which is 1

In [17]:
a=np.zeros(10)
print(a)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

13. Create a 3x3 identity matrix

In [18]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float

In [19]:
arr=np.array([1,2,3,4,5], dtype=np.float)
print(arr)

[1. 2. 3. 4. 5.]

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2

In [22]:
arr1=np.array([[1.,2.,3.], [4.,5.,6.]])
arr2=np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr1 * arr2)

[[ 0.  8.  3.]
 [28. 10. 18.]]

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [23]:
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [24]:
arr=np.arange(10)
odd_arr=arr[arr % 2==1]
odd_arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [25]:
odd_arr[0:]=-1
odd_arr

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [26]:
arr=np.arange(10)
print("Original Array: ",arr)
arr[5:9]=12
print("Replaces by 12: ",arr)

Original Array:  [0 1 2 3 4 5 6 7 8 9]
Replaces by 12:  [ 0  1  2  3  4 12 12 12 12  9]

20. Create a 2d array with 1 on the border and 0 inside

In [27]:
arr2d=np.ones((5,5))
print("Original Arry")
print(arr2d,"\n")
arr2d[1:4,1:4]=0
print("Changed Array")
print(arr2d)

Original Arry
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Changed Array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [28]:
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array: ")
print(arr2d,"\n")
arr2d[1][1]=12
print("Changed Array: ")
print(arr2d)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Changed Array:
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64

In [29]:
arr3d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original Arrray")
print(arr3d)
arr3d[0][0]=64
print("\nChanged Array")
print(arr3d)

Original Arrray
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Changed Array
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [30]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,"\n")
arr1=arr[0:1, 0:5].ravel()
print("1d Array")
print(arr1)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]

1d Array
[0 1 2 3 4]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [31]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,'\n')
arr1=arr[1:2, 0:5].ravel()
print("slice out the 2nd value from 2nd 1-D array")
arr1[1]

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]

slice out the 2nd value from 2nd 1-D array

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [32]:
arr=np.arange(0,10).reshape(2,5)
print("Original Array")
print(arr,'\n')
arr1=arr[0:2, 3:4]
print("Third column but only the first two rows")
print(arr1)

Original Array
[[0 1 2 3 4]
 [5 6 7 8 9]]

Third column but only the first two rows
[[3]
 [8]]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [33]:
arr=np.random.randn(10,10)
print("Original Array")
print(arr,'\n')
maximum=np.amax(arr)
print("Maximum Value")
print(maximum,'\n')
minimum=np.amin(arr)
print("Minimum Value")
print(minimum)

Original Array
[[ 0.25540401 -1.02966892 -0.50695983 -0.77283195  1.03129465  0.27103751
   1.57707949 -0.77294301  0.56058146  0.75037624]
 [-0.23492374  0.5568266   0.84299559  0.57194036 -0.67340804  0.35552832
  -0.35176655  0.09748975  0.88535291  1.91331673]
 [ 0.06395557  0.93440885 -0.99367014 -1.22048507 -0.08386253 -1.3129905
   0.0816586  -0.41671181  0.72781904  1.61766176]
 [-1.36402113 -0.37724411  0.07523559 -0.9735218   0.33025734  0.15763441
  -0.95342791  0.52745983 -2.12472477  1.11221085]
 [ 1.76421502 -1.26769103  1.52510418 -0.3872099   1.49256667 -0.27830518
  -0.56853094  0.62902706  1.19651517  0.54057748]
 [ 2.18613668  0.35763904  0.0811723  -1.37581862  1.05946133 -1.59010779
   1.20694528  0.6412056   1.0057231   0.36869536]
 [-1.17685683 -0.09012803  0.39169483 -0.04367007  1.41491714 -0.24209826
   0.23947429  0.61649452  1.30910369  0.27050875]
 [ 0.15883485 -0.63381114  1.22906432  0.23063991 -0.26590232  1.07521256
   1.47945998  0.76064746 -0.67147791  0.69818362]
 [ 0.53865143  0.6807481   0.50325054 -0.30437632 -0.19567981  0.22618923
  -0.28448751 -0.90785064  0.437299   -1.15743236]
 [ 0.25437662  1.3076824   0.68095967 -0.10951192  0.29587631 -2.19023006
  -0.81326349 -0.81784341 -0.12444391 -0.37258578]]

Maximum Value
2.1861366826198823

Minimum Value
-2.1902300607696557

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b

In [34]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b,'\n')
print("Common Items Between a and b")
print(a==b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]

Common Items Between a and b
[False  True False  True False  True False  True False False]

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match

In [35]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(np.in1d(a, b))[0]
c

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.04957523, -0.75688379, -0.51893227, -0.13840716],
       [-0.34209692, -0.10789075, -0.57691646, -0.0117872 ],
       [-0.07410157,  0.41052451,  0.77179619,  0.86869432],
       [ 0.5317643 , -0.81480746,  1.31323616, -0.23036212],
       [ 0.32511977,  1.54612609, -1.54718784,  0.59059078]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**

In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names!='Joe'],'\n')
print(data[names!='will'])

[[-1.15099776 -0.0263548  -1.2617876  -0.51906184]
 [-0.03341402  0.03470496  1.48119796  1.16310493]
 [-2.44809838 -0.43413214 -0.21969946  0.61146423]
 [-0.3243172   0.47466921 -0.03588681 -1.91626781]]

[[-1.15099776 -0.0263548  -1.2617876  -0.51906184]
 [-0.623497   -1.84964414  0.60161062 -0.84657366]
 [-0.03341402  0.03470496  1.48119796  1.16310493]
 [-2.44809838 -0.43413214 -0.21969946  0.61146423]
 [-0.3243172   0.47466921 -0.03588681 -1.91626781]
 [-1.52901284  2.19976512 -1.58208843 -0.17766877]
 [ 1.4548991   0.02926192 -1.42323265 -2.22872191]]

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
arr=np.linspace(1,14,15).reshape(5,3)
print(arr)
np.shape(arr)

[[ 1.          1.92857143  2.85714286]
 [ 3.78571429  4.71428571  5.64285714]
 [ 6.57142857  7.5         8.42857143]
 [ 9.35714286 10.28571429 11.21428571]
 [12.14285714 13.07142857 14.        ]]

(5, 3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
arr=np.linspace(1,15,16).reshape(2,2,4)
print(arr)
print(np.shape(arr))

[[[ 1.          1.93333333  2.86666667  3.8       ]
  [ 4.73333333  5.66666667  6.6         7.53333333]]

 [[ 8.46666667  9.4        10.33333333 11.26666667]
  [12.2        13.13333333 14.06666667 15.        ]]]
(2, 2, 4)

33. Swap axes of the array you created in Question 32

In [39]:
arr1=arr.swapaxes(1,2)
arr1

array([[[ 1.        ,  4.73333333],
        [ 1.93333333,  5.66666667],
        [ 2.86666667,  6.6       ],
        [ 3.8       ,  7.53333333]],

       [[ 8.46666667, 12.2       ],
        [ 9.4       , 13.13333333],
        [10.33333333, 14.06666667],
        [11.26666667, 15.        ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
arr=np.arange(10)
print(arr)
arr1=np.sqrt(arr)
print(arr1)
arr1[arr1<0.5]=0
arr1

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
print("Array 1\n",arr1)
print("\nArray 2\n",arr2)
arr=np.maximum(arr1,arr2)
print("\nMaximum Array Between Arrar1 and Array2\n",arr)

Array 1
 [-1.59621123  1.32660869  0.33609405 -0.35515357  0.78505812  0.69195372
 -0.43259481  0.35060399 -1.36701096  0.26821989  0.57401188 -0.8013141 ]

Array 2
 [ 0.76150476  0.54477961 -0.35353437 -0.10284474 -2.03485943  0.3547995
 -0.99691871  0.88090252 -1.19868594 -1.42433892 -1.18226052  0.67908633]

Maximum Array Between Arrar1 and Array2
 [ 0.76150476  1.32660869  0.33609405 -0.10284474  0.78505812  0.69195372
 -0.43259481  0.88090252 -1.19868594  0.26821989  0.57401188  0.67908633]

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!

In [42]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arr=np.unique(names)
arr

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b

In [43]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([5, 6, 7, 8, 9])
arr=np.setdiff1d(a, b)
arr

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])

In [44]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print("Samlpe Array\n",sampleArray)
print("\nNew Column\n",newColumn)
del_arr=np.delete(sampleArray,1,1)
print("\nDeteted Array\n",del_arr)
col1=del_arr[0:3,0:1].reshape(1,3)
col2=del_arr[0:3,1:2].reshape(1,3)
col3=np.dstack((col1, newColumn))
arr=np.dstack((col3, col2))
print("\nReplaces Column Array\n",arr)

Samlpe Array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

New Column
 [[10 10 10]]

Deteted Array
 [[34 73]
 [82 12]
 [53 66]]

Replaces Column Array
 [[[34 10 73]
  [82 10 12]
  [53 10 66]]]

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix

In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product=np.dot(x,y)
print("Dot Product of Matrix\n",dot_product)

Dot Product of Matrix
 [[ 28.  64.]
 [ 67. 181.]]

40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
arr=np.arange(20)
print("Array\n",arr)
arr1=arr.cumsum()
print("\nCumulative Sum\n",arr1)

Array
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Cumulative Sum
 [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]